### ISSUE TITLE
Error activating binder environment on DataLab

### ISSUE THREAD

**Issue by leehart** [malariagen/binder#104]
I'm trying to activate this Python environment so that I have the `gsutil` command, for Bash scripts.

```
leehart@jupyter-leehart:~/gitRepos/vector-ops$ source binder/env.sh
Could not find conda environment: vector-ops-v3.0.0
You can list all discoverable environments with `conda info --envs`.

conda not installed
```
```
leehart@jupyter-leehart:~/gitRepos/vector-ops$ conda info --envs
# conda environments:
#
abafar-20210701a         /home/conda/environments/abafar-20210701a
abafar-20210705a         /home/conda/environments/abafar-20210705a
basic                    /home/conda/environments/basic
binder-v3.0.0            /home/conda/environments/binder-v3.0.0
dashboard                /home/conda/environments/dashboard
default                  /home/conda/environments/default
geo-20210706             /home/conda/environments/geo-20210706
hts-20210727             /home/conda/environments/hts-20210727
base                  *  /home/jovyan/gitRepos/vector-ops/binder/deps/conda
```

Do I need to update the label `vector-ops-v3.0.0` to `binder-v3.0.0` somewhere (or vice versa)?

Or perhaps this is the wrong way to get `gsutil`? (The old DataLab had it pre-installed, and before that we had to install it manually via the command line, but my unreliable memory tells me that activating an environment was the way to get it.)

**Comment by leehart** [comment]
I suspect this might be due to an uncompleted `./binder/install-conda.sh` due to using a micro VM.

**Comment by leehart** [comment]
I'm thinking of converting the Bash scripts to notebooks, just to run `gsutil` with the `binder-v3.0.0` kernel, but this would still leave the question/problem hanging.
Another workaround might be `sudo pip install gsutil`, but I don't think that's what we want, long term.

**Comment by alimanfoo** [comment]
Hi @leehart, on datalab abafar you can just activate the pre-installed binder-v3.0.0 environment, i.e. from the terminal:

```
conda activate binder-v3.0.0
```

That includes `gsutil`. 

Running `./binder/install-conda.sh` or `source binder/env.sh` are only intended for when you're working on your own computer, not on datalab.

**Comment by leehart** [comment]
Thanks @alimanfoo

**Comment by alimanfoo** [comment]
No problem, sorry for any confusion.
