### ISSUE TITLE
mac conda install errors

### ISSUE THREAD

**Issue by tnguyensanger** [malariagen/binder#11]
I got the following errors while running install-conda.sh on a mac 

$  ./binder/install-conda.sh
bash: Miniconda3-latest-MaxOSX-x86_64.sh: No such file or directory

One hacky way to resolve this is by modifying the script:

````
if [ "$(uname)" == "Darwin" ]; then
....
    chmod ug+x Miniconda3-latest-MacOSX-x86_64.sh
    # install miniconda
   ./Miniconda3-latest-MacOSX-x86_64.sh -b -p ../$CONDADIR
````

**Comment by alimanfoo** [comment]
Thanks @tnguyensanger, this is fixed (#4, #7) but I haven't updated the submodule in vector-ops, will do so.
