### ISSUE TITLE
Newer snakemake version 

### ISSUE THREAD

**Issue by amakunin** [malariagen/binder#12]
Hi @alimanfoo @hardingnj

Just realized I was using a newer version of snakemake for my workflows. The newest version is
`snakemake=5.3.1`, which seemingly has CWL export option. But feature that I used (`directory` output type) was added in `snakemake=5.2.0`. Can we update the environment.yml:L51 to either of those?

As a side-effect it might be needed to introduce a couple of changes in the pipelines, as the `directory` usage is not backwards compatible, i.e. mandatory in newer versions and cannot be used in older versions.

Here's the line: https://github.com/malariagen/binder/blob/7c0086d14bbdf6d0e3bbf18f55cc2df1e8801238/environment.yml#L51

**Comment by amakunin** [comment]
See also [snakemake changelog](https://snakemake.readthedocs.io/en/stable/project_info/history.html#id9)

**Comment by amakunin** [comment]
xref https://github.com/malariagen/binder/issues/6#issuecomment-408391148

**Comment by alimanfoo** [comment]
Hi @amakunin, please feel free to make a PR with an upgrade to the snakemake version. If you want to also upgrade other packages while you are at it, that would also be fine, equally fine if you just want to upgrade snakemake and leave other upgrades for later.

**Comment by amakunin** [comment]
Hi @alimanfoo. On it. Still, I cannot push to the binder repo. Could you give me the writing rights?

**Comment by alimanfoo** [comment]
Thanks @podpearson. I gave @malariagen/resource-centre write too, in case anyone outside vector-core wants to make a PR.

FWIW this repo is public and so you can also fork it to your own account and make a PR from there. But also happy for PRs to come in from branches within malariagen/binder. And also makes sense for others to have write access so they can merge PRs (e.g., @podpearson, @hardingnj, @amakunin, happy for you to merge PRs).
