### ISSUE TITLE
jupyter nbconvert fails due to lxml change

### ISSUE THREAD

**Issue by alimanfoo** [malariagen/binder#137]
Trying to use `jupyter nbconvert` with binder 4.7.0 hits same issue as https://github.com/broadinstitute/CellBender/issues/348

**Comment by ahernank** [comment]
We've encountered this issue before too in https://github.com/malariagen/vector-data/pull/62. I've been meaning to add an issue here too, sorry!

**Comment by alimanfoo** [comment]
No worries!
