### ISSUE TITLE
Documenting pitfalls in binder testing

### ISSUE THREAD

**Issue by amakunin** [malariagen/binder#14]
Here's how I test binder updates in the independent repo.  Tricky points here are to deactivate any envs and to do `cd ..` prior to conda installation to avoid an ambiguous error `SpecNotFound: Invalid name, try the format: user/package`.

Maybe this procedure can be improved and then documented in the readme? 

---

Clone the repo, create new branch
```
git clone git@github.com:malariagen/binder.git
cd binder
git checkout -b issue_name
git push --set-upstream origin issue_name
# make some changes
```
Test if it did not break the installation process, but first make sure that no environment is activated, otherwise run `source deactivate`. Then do
```
cd ..
./binder/install_conda.sh
source ./binder/env.sh
# check package versions and resolve version conflicts
```
If all went well, push changes
```
cd binder
git add environment.yml
git commit -m '###'
git push
# do PR
```
Optional clean-up
```
rm -r ../deps
```

**Comment by alimanfoo** [comment]
Thanks @amakunin. I recently merged in some improvements to the README from @podpearson, but your content would be a useful addition. Please feel free to submit a PR with changes to README.

**Comment by amakunin** [comment]
@alimanfoo I'm now not sure this section in the README will be necessary given that Travis CI check includes whole installation process, so the problems can be caught at this stage. What do you think?
