### ISSUE TITLE
Add deps to .gitignore

### ISSUE THREAD

**Issue by podpearson** [malariagen/binder#18]
This will ensure that if you install environment from a local clone of binder, the deps directory will not be tracked in github

**Comment by podpearson** [comment]
Closing as this was a stupid idea (see @amakunin comments at #19 )

**Comment by alimanfoo** [comment]
Actually not a stupid idea, if we moved the deps directory to be within the binder sub-folder (i.e., binder/deps), which would be better for local testing. That would require everyone to rerun install-conda.sh, but they'll need to do that anyway with various upgrades coming in (#17, #20 etc). Worth considering IMO.

**Comment by alimanfoo** [comment]
I think I'm going to do this, would be cleaner.
