### ISSUE TITLE
Fix msprime import error

### ISSUE THREAD

**Issue by podpearson** [malariagen/binder#30]
The latest travis CI build (see https://github.com/malariagen/binder/pull/29 and https://travis-ci.org/malariagen/binder/jobs/483115513) failed on linux as msprime could not be imported.

**Comment by alimanfoo** [comment]
raised upstream: https://github.com/tskit-dev/msprime/issues/694

**Comment by alimanfoo** [comment]
Short term fix here would be to install msprime via pip.
