### ISSUE TITLE
Add binder update instructions for non-master branch

### ISSUE THREAD

**Issue by amakunin** [malariagen/binder#35]
Hi @alimanfoo 

Frequent use case of binder update is its application to non-master working branch. I believe you posted commands on how to do it, but I lost track of those. Maybe you could add this list of commands to binder readme?

**Comment by amakunin** [comment]
Also, when someone else updated binder in master and I want to update binder, I would do
```
cd /path/to/vobs-repo
git checkout master
git pull --recursive
binder/install-conda.sh
```
and then 
```
source binder/env.sh
```

Is this a correct strategy?

**Comment by alimanfoo** [comment]
Hi Alex,

> Frequent use case of binder update is its application to non-master
> working branch. I believe you posted commands on how to do it, but I lost
> track of those. Maybe you could add this list of commands to binder readme?
>
Not quite sure what you mean there. Could you give an example? Thanks.

**Comment by alimanfoo** [comment]
On Thu, 21 Feb 2019 at 11:46, Alex Makunin <notifications@github.com> wrote:

> Also, when someone else updated binder in master and I want to update
> binder, I would do
>
> cd /path/to/vobs-repo
> git checkout master
> git pull --recursive
> binder/install-conda.sh
>
> I normally do:

cd /path/to/vobs-repo
git checkout master
git pull
git submodule update --init
./binder/install-conda.sh

...however looking at the docs for git pull you may be able to shorten this
a bit by doing:

cd /path/to/vobs-repo
git checkout master
git pull --recurse-submodules
./binder/install-conda.sh

> and then
>
> source binder/env.sh
>
> Yes.
