### ISSUE TITLE
Rename environment YAML files

### ISSUE THREAD

**Issue by alimanfoo** [malariagen/binder#57]
Currently the main linux environment file is called "environment-pinned-linux.yml". This is nice and descriptive, however it means that this module can no longer be used as a submodule to create mybinder-launchable repos, because [mybinder expects a file called "environment.yml"](https://mybinder.readthedocs.io/en/latest/sample_repos.html#conda-environment-with-environment-yml).

Proposed to change the name of "environment-pinned-linux.yml" to "environment.yml". For simplicity, proposed to also rename "environment-pinned-osx.yml" to "environment-osx.yml".

**Comment by hardingnj** [comment]
No issues here

**Comment by alimanfoo** [comment]
As suggested by @slejdops, we resolved this by adding a symlink "environment.yml" pointing to "environment-pinned-linux.yml".
