### ISSUE TITLE
Add umap-learn

### ISSUE THREAD

**Issue by amakunin** [malariagen/binder#62]
@alimanfoo mentioned that might be worthwhile

Simply running
```
conda install -c conda-forge umap-learn
```
from within binder env results in a bunch of version conflicts. Is there a better way around it?

**Comment by alimanfoo** [comment]
This should be possible to add umap-learn and get the environment to solve, we meet the [package requirements](https://github.com/conda-forge/umap-learn-feedstock/blob/master/recipe/meta.yaml). If someone wants to explore this, I'd suggest trying it locally, e.g., add umap-learn to requirements-conda.txt, delete the pinned environment files, and try running install-conda.sh and see if it solves.

**Comment by slejdops** [comment]
Added umap-learn to requirements-conda.txt 
Running install-conda.sh on a linux VM

**Comment by slejdops** [comment]
environment solves with umap-learn

**Comment by alimanfoo** [comment]
Thanks @slejdops, that's good to know. Could you make a PR? Initial PR would edit requirements-conda.txt to add umap-learn, and would also deleted the pinned environment files. Then let CI rebuild the pinned files and copy-paste them out of the logs back into the pinned environment files as usual.
