### ISSUE TITLE
seaborn-matplotlib version conflict

### ISSUE THREAD

**Issue by amakunin** [malariagen/binder#63]
Heatmap plotting is broken when using combination 
```
seaborn=0.9.0
matplotlib=3.1.1
```
This is a documented problem https://github.com/mwaskom/seaborn/issues/1773. My solution was to downgrade matplotlib to `matplotlib=3.1.0`. The bug should be also fixed in `matplotlib=3.1.2`, which is currently not released.

**Comment by cclarkson** [comment]
@amakunin - as discussed on Standup call, this [issue](https://github.com/matplotlib/matplotlib/issues/14751) has an example of how to get around the heatmap issue without downgrading matplotlib, it is a bit fiddly but it worked for me.

**Comment by alimanfoo** [comment]
Binder is now at matplotlib 3.1.2, hopefully this is resolved, please feel free to reopen if not.
