### ISSUE TITLE
owslib problem: fix found

### ISSUE THREAD

**Issue by amakunin** [malariagen/binder#75]
Doing v4.2.1 installation I encountered an error
```
conda.exceptions.ResolvePackageNotFound: 
  - owslib==0.19.0=py_1
```

It seems to happen because this package is [labelled](https://anaconda.org/conda-forge/owslib/files) `broken` in conda-forge

Solution that worked for me: replace an entry in pinned environment to 
```
  - owslib=0.19.0=py_2
```

**Comment by alimanfoo** [comment]
Thanks @amakunin. I'm currently getting two packages missing:

```
conda.exceptions.ResolvePackageNotFound: 
  - gdk-pixbuf==2.36.12=haf2c3b9_1004
  - owslib==0.19.0=py_1
```

We should update the pinned environments.

Btw another possible workaround is to add the conda-forge/label/broken channel to the channel list in the environment file. E.g., manually edit so it looks like this:

```
$ head binder/environment-pinned-linux.yml 
name: malariagen-291e88e
channels:
  - conda-forge
  - bioconda
  - defaults
  - conda-forge/label/broken
```
