### ISSUE TITLE
Request: new snakemake version

### ISSUE THREAD

**Issue by amakunin** [malariagen/binder#80]
Hi, can we include [snakemake>=5.10.0](https://snakemake.readthedocs.io/en/stable/project_info/history.html#changelog) in the next binder release?

It introduces integration with jupyter notebooks, which basically means no need to convert code into plain python scripts after development in jupyter. I wanted to play around with this feature, but was carried away by other projects. Thus, leaving a reminder here.

**Comment by alimanfoo** [comment]
Resolved via #86, available in v2.5.0.
