### ISSUE TITLE
Pinned environments with conda spec files

### ISSUE THREAD

**Issue by amakunin** [malariagen/binder#81]
Looking through [conda docs](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#building-identical-conda-environments), it seems that the recommended way of creating the identical environment is creation of spec files with 

`conda list --explicit > spec-file.txt`

Which then can be used instead of yml

`conda create --name myenv --file spec-file.txt`

I wonder if we could/should use those spec files instead of pinned environments as linux/MacOs specific snapshots. Or am I missing some point here?

**Comment by alimanfoo** [comment]
Hi @amakunin, sorry I missed this at the time. Yes a spec file would be ideal, I did contemplate that. The main blocker IIRC is that it won't include any pip installed packages. The benefit of the environment files is that they include both conda and pip packages.
